---
abstract: 'quick and lazy way to add delicious.com bookmarks.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Lazyd
no_index:
  directory:
    - inc
    - t
requires:
  Net::Delicious: 1.13
  URI::Title: 1.82
  YAML::Tiny: 1.36
version: 0.01
